export const RESUME_URL = "https://drive.google.com/file/d/1ULhS0OUbMZfVxKSwqAwkOLHw5cDDfnbu/view?usp=sharing"
export const PORTFOLIO_REPO_URL = "https://github.com/leticia-chijo/portfolio"
export const GITHUB_URL = "https://github.com/leticia-chijo"
export const LINKEDIN_URL = "https://www.linkedin.com/in/leticia-chijo"
export const INSTAGRAM_URL = "https://www.instagram.com/leticia.chijo/"
export const INTRODUCTION_URL = "https://drive.google.com/file/d/1UviNik3RZhPkaWsKadgB5GeFkNx5A5aB/view?usp=drive_link"
export const EMAIL = "leticia.chijo@gmail.com"
